// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: proto/sync/v1/sync.proto

// Cloud Sync Service contract (Proto Contract Book §4).
// This file is the single source of truth for both the Dart local-server
// client and the Go cloud implementation.

package syncpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SyncService_PushBatch_FullMethodName   = "/amarhisab.sync.v1.SyncService/PushBatch"
	SyncService_PullChanges_FullMethodName = "/amarhisab.sync.v1.SyncService/PullChanges"
	SyncService_SyncStream_FullMethodName  = "/amarhisab.sync.v1.SyncService/SyncStream"
)

// SyncServiceClient is the client API for SyncService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SyncServiceClient interface {
	// Push local changes to the cloud.
	PushBatch(ctx context.Context, in *PushBatchRequest, opts ...grpc.CallOption) (*PushBatchResponse, error)
	// Pull remote changes since the last known sequence.
	PullChanges(ctx context.Context, in *PullRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChangeEvent], error)
	// (Future) Bidirectional real-time sync stream.
	SyncStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChangeEvent, ChangeEvent], error)
}

type syncServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSyncServiceClient(cc grpc.ClientConnInterface) SyncServiceClient {
	return &syncServiceClient{cc}
}

func (c *syncServiceClient) PushBatch(ctx context.Context, in *PushBatchRequest, opts ...grpc.CallOption) (*PushBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushBatchResponse)
	err := c.cc.Invoke(ctx, SyncService_PushBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncServiceClient) PullChanges(ctx context.Context, in *PullRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChangeEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SyncService_ServiceDesc.Streams[0], SyncService_PullChanges_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PullRequest, ChangeEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SyncService_PullChangesClient = grpc.ServerStreamingClient[ChangeEvent]

func (c *syncServiceClient) SyncStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChangeEvent, ChangeEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SyncService_ServiceDesc.Streams[1], SyncService_SyncStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChangeEvent, ChangeEvent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SyncService_SyncStreamClient = grpc.BidiStreamingClient[ChangeEvent, ChangeEvent]

// SyncServiceServer is the server API for SyncService service.
// All implementations must embed UnimplementedSyncServiceServer
// for forward compatibility.
type SyncServiceServer interface {
	// Push local changes to the cloud.
	PushBatch(context.Context, *PushBatchRequest) (*PushBatchResponse, error)
	// Pull remote changes since the last known sequence.
	PullChanges(*PullRequest, grpc.ServerStreamingServer[ChangeEvent]) error
	// (Future) Bidirectional real-time sync stream.
	SyncStream(grpc.BidiStreamingServer[ChangeEvent, ChangeEvent]) error
	mustEmbedUnimplementedSyncServiceServer()
}

// UnimplementedSyncServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSyncServiceServer struct{}

func (UnimplementedSyncServiceServer) PushBatch(context.Context, *PushBatchRequest) (*PushBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PushBatch not implemented")
}
func (UnimplementedSyncServiceServer) PullChanges(*PullRequest, grpc.ServerStreamingServer[ChangeEvent]) error {
	return status.Error(codes.Unimplemented, "method PullChanges not implemented")
}
func (UnimplementedSyncServiceServer) SyncStream(grpc.BidiStreamingServer[ChangeEvent, ChangeEvent]) error {
	return status.Error(codes.Unimplemented, "method SyncStream not implemented")
}
func (UnimplementedSyncServiceServer) mustEmbedUnimplementedSyncServiceServer() {}
func (UnimplementedSyncServiceServer) testEmbeddedByValue()                     {}

// UnsafeSyncServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SyncServiceServer will
// result in compilation errors.
type UnsafeSyncServiceServer interface {
	mustEmbedUnimplementedSyncServiceServer()
}

func RegisterSyncServiceServer(s grpc.ServiceRegistrar, srv SyncServiceServer) {
	// If the following call panics, it indicates UnimplementedSyncServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SyncService_ServiceDesc, srv)
}

func _SyncService_PushBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServiceServer).PushBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncService_PushBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServiceServer).PushBatch(ctx, req.(*PushBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncService_PullChanges_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PullRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SyncServiceServer).PullChanges(m, &grpc.GenericServerStream[PullRequest, ChangeEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SyncService_PullChangesServer = grpc.ServerStreamingServer[ChangeEvent]

func _SyncService_SyncStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SyncServiceServer).SyncStream(&grpc.GenericServerStream[ChangeEvent, ChangeEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SyncService_SyncStreamServer = grpc.BidiStreamingServer[ChangeEvent, ChangeEvent]

// SyncService_ServiceDesc is the grpc.ServiceDesc for SyncService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SyncService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "amarhisab.sync.v1.SyncService",
	HandlerType: (*SyncServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushBatch",
			Handler:    _SyncService_PushBatch_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PullChanges",
			Handler:       _SyncService_PullChanges_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SyncStream",
			Handler:       _SyncService_SyncStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/sync/v1/sync.proto",
}
