// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: proto/sync/v1/sync.proto

// Cloud Sync Service contract (Proto Contract Book §4).
// This file is the single source of truth for both the Dart local-server
// client and the Go cloud implementation.

package syncpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushBatchRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DeviceId           string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	LastSyncedSequence int64                  `protobuf:"varint,2,opt,name=last_synced_sequence,json=lastSyncedSequence,proto3" json:"last_synced_sequence,omitempty"`
	Changes            []*ChangeEvent         `protobuf:"bytes,3,rep,name=changes,proto3" json:"changes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PushBatchRequest) Reset() {
	*x = PushBatchRequest{}
	mi := &file_proto_sync_v1_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushBatchRequest) ProtoMessage() {}

func (x *PushBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v1_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushBatchRequest.ProtoReflect.Descriptor instead.
func (*PushBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_sync_v1_sync_proto_rawDescGZIP(), []int{0}
}

func (x *PushBatchRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *PushBatchRequest) GetLastSyncedSequence() int64 {
	if x != nil {
		return x.LastSyncedSequence
	}
	return 0
}

func (x *PushBatchRequest) GetChanges() []*ChangeEvent {
	if x != nil {
		return x.Changes
	}
	return nil
}

type PushBatchResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AcceptedSequence int64                  `protobuf:"varint,2,opt,name=accepted_sequence,json=acceptedSequence,proto3" json:"accepted_sequence,omitempty"`
	Conflicts        []*Conflict            `protobuf:"bytes,3,rep,name=conflicts,proto3" json:"conflicts,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PushBatchResponse) Reset() {
	*x = PushBatchResponse{}
	mi := &file_proto_sync_v1_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushBatchResponse) ProtoMessage() {}

func (x *PushBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v1_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushBatchResponse.ProtoReflect.Descriptor instead.
func (*PushBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_sync_v1_sync_proto_rawDescGZIP(), []int{1}
}

func (x *PushBatchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PushBatchResponse) GetAcceptedSequence() int64 {
	if x != nil {
		return x.AcceptedSequence
	}
	return 0
}

func (x *PushBatchResponse) GetConflicts() []*Conflict {
	if x != nil {
		return x.Conflicts
	}
	return nil
}

type Conflict struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChangeId      string                 `protobuf:"bytes,1,opt,name=change_id,json=changeId,proto3" json:"change_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	LocalVersion  []byte                 `protobuf:"bytes,3,opt,name=local_version,json=localVersion,proto3" json:"local_version,omitempty"`
	RemoteVersion []byte                 `protobuf:"bytes,4,opt,name=remote_version,json=remoteVersion,proto3" json:"remote_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Conflict) Reset() {
	*x = Conflict{}
	mi := &file_proto_sync_v1_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conflict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conflict) ProtoMessage() {}

func (x *Conflict) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v1_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conflict.ProtoReflect.Descriptor instead.
func (*Conflict) Descriptor() ([]byte, []int) {
	return file_proto_sync_v1_sync_proto_rawDescGZIP(), []int{2}
}

func (x *Conflict) GetChangeId() string {
	if x != nil {
		return x.ChangeId
	}
	return ""
}

func (x *Conflict) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Conflict) GetLocalVersion() []byte {
	if x != nil {
		return x.LocalVersion
	}
	return nil
}

func (x *Conflict) GetRemoteVersion() []byte {
	if x != nil {
		return x.RemoteVersion
	}
	return nil
}

type PullRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DeviceId           string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	LastRemoteSequence int64                  `protobuf:"varint,2,opt,name=last_remote_sequence,json=lastRemoteSequence,proto3" json:"last_remote_sequence,omitempty"`
	BusinessId         string                 `protobuf:"bytes,3,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PullRequest) Reset() {
	*x = PullRequest{}
	mi := &file_proto_sync_v1_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullRequest) ProtoMessage() {}

func (x *PullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v1_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullRequest.ProtoReflect.Descriptor instead.
func (*PullRequest) Descriptor() ([]byte, []int) {
	return file_proto_sync_v1_sync_proto_rawDescGZIP(), []int{3}
}

func (x *PullRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *PullRequest) GetLastRemoteSequence() int64 {
	if x != nil {
		return x.LastRemoteSequence
	}
	return 0
}

func (x *PullRequest) GetBusinessId() string {
	if x != nil {
		return x.BusinessId
	}
	return ""
}

type ChangeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChangeId      string                 `protobuf:"bytes,1,opt,name=change_id,json=changeId,proto3" json:"change_id,omitempty"` // UUID
	EntityType    string                 `protobuf:"bytes,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntityId      int64                  `protobuf:"varint,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Operation     string                 `protobuf:"bytes,4,opt,name=operation,proto3" json:"operation,omitempty"`                  // "INSERT", "UPDATE", "DELETE"
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`                      // JSON
	OldValues     []byte                 `protobuf:"bytes,6,opt,name=old_values,json=oldValues,proto3" json:"old_values,omitempty"` // JSON
	TimestampMs   int64                  `protobuf:"varint,7,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Sequence      int64                  `protobuf:"varint,8,opt,name=sequence,proto3" json:"sequence,omitempty"` // device-local sequence
	DeviceId      string                 `protobuf:"bytes,9,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeEvent) Reset() {
	*x = ChangeEvent{}
	mi := &file_proto_sync_v1_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeEvent) ProtoMessage() {}

func (x *ChangeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sync_v1_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeEvent.ProtoReflect.Descriptor instead.
func (*ChangeEvent) Descriptor() ([]byte, []int) {
	return file_proto_sync_v1_sync_proto_rawDescGZIP(), []int{4}
}

func (x *ChangeEvent) GetChangeId() string {
	if x != nil {
		return x.ChangeId
	}
	return ""
}

func (x *ChangeEvent) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *ChangeEvent) GetEntityId() int64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *ChangeEvent) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *ChangeEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ChangeEvent) GetOldValues() []byte {
	if x != nil {
		return x.OldValues
	}
	return nil
}

func (x *ChangeEvent) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *ChangeEvent) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ChangeEvent) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

var File_proto_sync_v1_sync_proto protoreflect.FileDescriptor

const file_proto_sync_v1_sync_proto_rawDesc = "" +
	"\n" +
	"\x18proto/sync/v1/sync.proto\x12\x11amarhisab.sync.v1\"\x9b\x01\n" +
	"\x10PushBatchRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x120\n" +
	"\x14last_synced_sequence\x18\x02 \x01(\x03R\x12lastSyncedSequence\x128\n" +
	"\achanges\x18\x03 \x03(\v2\x1e.amarhisab.sync.v1.ChangeEventR\achanges\"\x95\x01\n" +
	"\x11PushBatchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12+\n" +
	"\x11accepted_sequence\x18\x02 \x01(\x03R\x10acceptedSequence\x129\n" +
	"\tconflicts\x18\x03 \x03(\v2\x1b.amarhisab.sync.v1.ConflictR\tconflicts\"\x8b\x01\n" +
	"\bConflict\x12\x1b\n" +
	"\tchange_id\x18\x01 \x01(\tR\bchangeId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12#\n" +
	"\rlocal_version\x18\x03 \x01(\fR\flocalVersion\x12%\n" +
	"\x0eremote_version\x18\x04 \x01(\fR\rremoteVersion\"}\n" +
	"\vPullRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x120\n" +
	"\x14last_remote_sequence\x18\x02 \x01(\x03R\x12lastRemoteSequence\x12\x1f\n" +
	"\vbusiness_id\x18\x03 \x01(\tR\n" +
	"businessId\"\x9b\x02\n" +
	"\vChangeEvent\x12\x1b\n" +
	"\tchange_id\x18\x01 \x01(\tR\bchangeId\x12\x1f\n" +
	"\ventity_type\x18\x02 \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\x03R\bentityId\x12\x1c\n" +
	"\toperation\x18\x04 \x01(\tR\toperation\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"old_values\x18\x06 \x01(\fR\toldValues\x12!\n" +
	"\ftimestamp_ms\x18\a \x01(\x03R\vtimestampMs\x12\x1a\n" +
	"\bsequence\x18\b \x01(\x03R\bsequence\x12\x1b\n" +
	"\tdevice_id\x18\t \x01(\tR\bdeviceId2\x88\x02\n" +
	"\vSyncService\x12V\n" +
	"\tPushBatch\x12#.amarhisab.sync.v1.PushBatchRequest\x1a$.amarhisab.sync.v1.PushBatchResponse\x12O\n" +
	"\vPullChanges\x12\x1e.amarhisab.sync.v1.PullRequest\x1a\x1e.amarhisab.sync.v1.ChangeEvent0\x01\x12P\n" +
	"\n" +
	"SyncStream\x12\x1e.amarhisab.sync.v1.ChangeEvent\x1a\x1e.amarhisab.sync.v1.ChangeEvent(\x010\x01BAZ?github.com/amarhisab/amar-hisab/cloud/sync/proto/sync/v1;syncpbb\x06proto3"

var (
	file_proto_sync_v1_sync_proto_rawDescOnce sync.Once
	file_proto_sync_v1_sync_proto_rawDescData []byte
)

func file_proto_sync_v1_sync_proto_rawDescGZIP() []byte {
	file_proto_sync_v1_sync_proto_rawDescOnce.Do(func() {
		file_proto_sync_v1_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sync_v1_sync_proto_rawDesc), len(file_proto_sync_v1_sync_proto_rawDesc)))
	})
	return file_proto_sync_v1_sync_proto_rawDescData
}

var file_proto_sync_v1_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_sync_v1_sync_proto_goTypes = []any{
	(*PushBatchRequest)(nil),  // 0: amarhisab.sync.v1.PushBatchRequest
	(*PushBatchResponse)(nil), // 1: amarhisab.sync.v1.PushBatchResponse
	(*Conflict)(nil),          // 2: amarhisab.sync.v1.Conflict
	(*PullRequest)(nil),       // 3: amarhisab.sync.v1.PullRequest
	(*ChangeEvent)(nil),       // 4: amarhisab.sync.v1.ChangeEvent
}
var file_proto_sync_v1_sync_proto_depIdxs = []int32{
	4, // 0: amarhisab.sync.v1.PushBatchRequest.changes:type_name -> amarhisab.sync.v1.ChangeEvent
	2, // 1: amarhisab.sync.v1.PushBatchResponse.conflicts:type_name -> amarhisab.sync.v1.Conflict
	0, // 2: amarhisab.sync.v1.SyncService.PushBatch:input_type -> amarhisab.sync.v1.PushBatchRequest
	3, // 3: amarhisab.sync.v1.SyncService.PullChanges:input_type -> amarhisab.sync.v1.PullRequest
	4, // 4: amarhisab.sync.v1.SyncService.SyncStream:input_type -> amarhisab.sync.v1.ChangeEvent
	1, // 5: amarhisab.sync.v1.SyncService.PushBatch:output_type -> amarhisab.sync.v1.PushBatchResponse
	4, // 6: amarhisab.sync.v1.SyncService.PullChanges:output_type -> amarhisab.sync.v1.ChangeEvent
	4, // 7: amarhisab.sync.v1.SyncService.SyncStream:output_type -> amarhisab.sync.v1.ChangeEvent
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_sync_v1_sync_proto_init() }
func file_proto_sync_v1_sync_proto_init() {
	if File_proto_sync_v1_sync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sync_v1_sync_proto_rawDesc), len(file_proto_sync_v1_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sync_v1_sync_proto_goTypes,
		DependencyIndexes: file_proto_sync_v1_sync_proto_depIdxs,
		MessageInfos:      file_proto_sync_v1_sync_proto_msgTypes,
	}.Build()
	File_proto_sync_v1_sync_proto = out.File
	file_proto_sync_v1_sync_proto_goTypes = nil
	file_proto_sync_v1_sync_proto_depIdxs = nil
}
