name: Build Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter Doctor (debug)
        run: flutter doctor -v

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: List project files (debug)
        run: dir flutter_app

      - name: Install dependencies
        working-directory: flutter_app
        run: flutter pub get

      - name: Analyze code (check for errors)
        working-directory: flutter_app
        run: flutter analyze

      - name: Build Windows EXE
        working-directory: flutter_app
        run: flutter build windows --release

      - name: List build output (debug)
        run: dir flutter_app\build\windows\runner\Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: amar-hisab-windows
          path: flutter_app/build/windows/runner/Release/
